const GET_COUNTRIES = "GET_COUNTRIES";
const GET_ACTIVITIES = "GET_ACTIVITIES";
const GET_DETAIL = "GET_DETAIL";
const SET_LOADING = "SET_LOADING";
const RESET_DETAIL = "RESET_DETAIL";
const ADD_NEW_ACTIVITY = "ADD_NEW_ACTIVITY";
const GET_ALL_REGIONS = "GET_ALL_REGIONS";
const GET_FILTERS = "GET_FILTERS";
const GET_ORDER = "GET_ORDER";
const SEARCH_BY_NAME = "SEARCH_BY_NAME";
const GET_FILTERS_CONTINENT = "GET_FILTERS_CONTINENT";
const GET_FILTERS_ACTIVITY = "GET_FILTERS_ACTIVITY";
const SET_ALL_COUNTRIES = "SET_ALL_COUNTRIES";

module.exports = {
  GET_COUNTRIES,
  GET_ACTIVITIES,
  GET_DETAIL,
  SET_LOADING,
  RESET_DETAIL,
  ADD_NEW_ACTIVITY,
  GET_ALL_REGIONS,
  GET_FILTERS,
  GET_ORDER,
  SEARCH_BY_NAME,
  GET_FILTERS_CONTINENT,
  GET_FILTERS_ACTIVITY,
  SET_ALL_COUNTRIES,
};
